### ISSUE TITLE
SIGSEGV?

### ISSUE THREAD

**Issue by anonproject** [joostjager/whatsat#6]
For some reason having SIGSEGV on mainnet while attempting to send a chat message:

```text
Send to xxxyyy [balance: 0 msat]
panic: runtime error: invalid memory address or nil pointer dereference                                               
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xa8bb8c

goroutine 52 [running]:
main.chat.func2.1(0xe8b0e0, 0xc00009a168, 0xc0000e21c0, 0xc000152240, 0x0, 0x3e8)
        /opt/whatsat/cmd_chat.go:301 +0x12c
created by main.chat.func2
        /opt/whatsat/cmd_chat.go:282 +0xa6d
```

```text
lnd --version
lnd version 0.10.0-beta.rc5 commit=v0.10.0-beta.rc5
```

**Comment by anonproject** [comment]
* It (lnd) does send the keysend payments with lncli BTW.

**Comment by curly60e** [comment]
> For some reason having SIGSEGV on mainnet while attempting to send a chat message:
> 
> ```
> Send to xxxyyy [balance: 0 msat]
> panic: runtime error: invalid memory address or nil pointer dereference                                               
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xa8bb8c
> 
> goroutine 52 [running]:
> main.chat.func2.1(0xe8b0e0, 0xc00009a168, 0xc0000e21c0, 0xc000152240, 0x0, 0x3e8)
>         /opt/whatsat/cmd_chat.go:301 +0x12c
> created by main.chat.func2
>         /opt/whatsat/cmd_chat.go:282 +0xa6d
> ```
> 
> ```
> lnd --version
> lnd version 0.10.0-beta.rc5 commit=v0.10.0-beta.rc5
> ```

I have the same issue.

**Comment by maddpaper** [comment]
same for me, I don't have any clue why is that and I have no idea how to solve it.
